[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run build && npx serve -s build -l $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production.variables]
REACT_APP_API_URL = "https://poker-backend-production.up.railway.app/api"
REACT_APP_WS_URL = "wss://poker-backend-production.up.railway.app/ws"